export const ROUTES = {
  HOME: '/',
  LEARN_MORE: '/learn-more',
  TRAIN: '/train',
  BUILDER: '/builder',
  PROFILE: '/profile',
  STATS: '/stats',
  CLASSES: '/classes',
  CLASS_DETAIL: '/classes/:classId',
  SIGNIN: '/finish-signin',
  PRIVACY: '/privacy',
  COPPA: '/coppa',
  FERPA: '/ferpa',
  TERMS: '/terms',
}
