import {
  Alert,
  Box,
  Container,
  Divider,
  Link,
  List,
  ListItem,
  ListItemText,
  Paper,
  Typography,
} from '@mui/material'
import { Link as RouterLink } from 'react-router-dom'
import { ROUTES } from '../../constants/routeConstants'

const PrivacyPolicyPage = () => {
  return (
    <Container maxWidth="md">
      <Paper sx={{ my: 4, p: { xs: 2, sm: 4 } }}>
        <Typography variant="h4" gutterBottom>
          Privacy Policy
        </Typography>

        <Typography variant="body2" color="text.secondary" component="p">
          Last updated: February 6, 2026
        </Typography>

        <Alert severity="info" sx={{ mb: 3 }}>
          This Privacy Policy explains how Math Builders / Multiplication
          Masters (the “App”) collects, uses, and shares information when you
          use the App.
        </Alert>

        <Box sx={{ mb: 3 }}>
          <Typography variant="subtitle2" gutterBottom>
            Related documents
          </Typography>
          <Typography variant="body2" color="text.secondary">
            <Link component={RouterLink} to={ROUTES.TERMS}>
              Terms of Service
            </Link>
            {' • '}
            <Link component={RouterLink} to={ROUTES.COPPA}>
              COPPA
            </Link>
            {' • '}
            <Link component={RouterLink} to={ROUTES.FERPA}>
              FERPA
            </Link>
          </Typography>
        </Box>

        <Typography variant="h6" gutterBottom>
          1) Who we are
        </Typography>
        <Typography variant="body1" component="p">
          The App is a time-driven spaced repetition system (SRS) for practicing
          multiplication facts. The App uses Firebase services (Authentication,
          Firestore, Cloud Functions, Storage, and (where available) Analytics)
          to provide accounts, sync progress, and enable features like session
          history and scene customization.
        </Typography>

        <Divider sx={{ my: 3 }} />

        <Typography variant="h6" gutterBottom>
          2) Information we collect
        </Typography>
        <Typography variant="body1" component="p">
          We collect information in three main ways: (a) information you
          provide, (b) information generated by your use of the App, and (c)
          technical data collected by our service providers.
        </Typography>

        <Typography variant="subtitle1" gutterBottom>
          A. Account and profile information
        </Typography>
        <List dense sx={{ mb: 2 }}>
          <ListItem>
            <ListItemText
              primary="Anonymous account identifier"
              secondary="If you use the App without signing in, Firebase Authentication may create an anonymous account ID so your progress can be saved on that device/session."
            />
          </ListItem>
          <ListItem>
            <ListItemText
              primary="Sign-in information"
              secondary="If you choose to sign in or upgrade an anonymous account, we may receive your email address and/or a provider identifier from Google or an email-link sign-in flow (depending on what you use)."
            />
          </ListItem>
          <ListItem>
            <ListItemText
              primary="Username and settings"
              secondary="We store a display username (which may be randomly generated) and preferences like theme and session length."
            />
          </ListItem>
        </List>

        <Typography variant="subtitle1" gutterBottom>
          B. Learning and usage data (App content)
        </Typography>
        <Typography variant="body1" component="p">
          The App is designed to adapt to performance. We store learning
          progress and session data, which may include:
        </Typography>
        <List dense sx={{ mb: 2 }}>
          <ListItem>
            <ListItemText
              primary="Practice data"
              secondary="Your multiplication facts, review history, spaced-repetition scheduling fields (e.g., next due time, box/interval/ease factor), and performance stats such as correct/incorrect counts and response-time averages."
            />
          </ListItem>
          <ListItem>
            <ListItemText
              primary="Session summaries"
              secondary="Information about sessions (e.g., start/end time, session length, and aggregate results)."
            />
          </ListItem>
          <ListItem>
            <ListItemText
              primary="Scene builder data"
              secondary="If you use the scene builder, we may store scene metadata and user-uploaded images/assets in Firebase Storage."
            />
          </ListItem>
        </List>

        <Typography variant="subtitle1" gutterBottom>
          C. Technical and analytics data
        </Typography>
        <Typography variant="body1" component="p">
          Our hosting and backend providers (including Firebase) may collect
          technical information such as device/browser type, IP address, app
          interaction events, and crash/diagnostic signals. Where Firebase
          Analytics is enabled and supported by your environment, Analytics may
          collect usage data to help us understand performance and improve the
          App.
        </Typography>

        <Divider sx={{ my: 3 }} />

        <Typography variant="h6" gutterBottom>
          3) How we use information
        </Typography>
        <List dense sx={{ mb: 2 }}>
          <ListItem>
            <ListItemText
              primary="Provide core functionality"
              secondary="Authenticate users, save and sync progress, schedule reviews, and load your selected packs/scenes."
            />
          </ListItem>
          <ListItem>
            <ListItemText
              primary="Improve and secure the App"
              secondary="Monitor performance, troubleshoot issues, prevent abuse, and maintain reliability."
            />
          </ListItem>
          <ListItem>
            <ListItemText
              primary="Communicate"
              secondary="Respond to support requests and feedback you submit through the App."
            />
          </ListItem>
        </List>

        <Divider sx={{ my: 3 }} />

        <Typography variant="h6" gutterBottom>
          4) How we share information
        </Typography>
        <Typography variant="body1" component="p">
          We do not sell your personal information. We share information only in
          the following circumstances:
        </Typography>
        <List dense sx={{ mb: 2 }}>
          <ListItem>
            <ListItemText
              primary="Service providers"
              secondary="We use Firebase (Google) to provide authentication, databases, cloud functions, file storage, and analytics. These providers process data on our behalf."
            />
          </ListItem>
          <ListItem>
            <ListItemText
              primary="Legal and safety"
              secondary="We may disclose information if we believe it is reasonably necessary to comply with law, protect users, or prevent fraud or security issues."
            />
          </ListItem>
          <ListItem>
            <ListItemText
              primary="Business changes"
              secondary="If the App is involved in a merger, acquisition, or asset transfer, information may be transferred as part of that transaction."
            />
          </ListItem>
        </List>

        <Divider sx={{ my: 3 }} />

        <Typography variant="h6" gutterBottom>
          5) Data retention
        </Typography>
        <Typography variant="body1" component="p">
          We keep account and progress data as long as needed to provide the
          App. If you delete your account or request deletion, we will take
          reasonable steps to delete or de-identify your personal information,
          subject to legal, security, and operational requirements (e.g.,
          backups and logs may persist for a limited period).
        </Typography>

        <Divider sx={{ my: 3 }} />

        <Typography variant="h6" gutterBottom>
          6) Security
        </Typography>
        <Typography variant="body1" component="p">
          We use reasonable administrative, technical, and organizational
          measures designed to protect information. No method of transmission or
          storage is 100% secure, and we cannot guarantee absolute security.
        </Typography>

        <Divider sx={{ my: 3 }} />

        <Typography variant="h6" gutterBottom>
          7) Children’s privacy (COPPA)
        </Typography>
        <Typography variant="body1" component="p">
          Please see our{' '}
          <Link component={RouterLink} to={ROUTES.COPPA}>
            COPPA notice
          </Link>{' '}
          for additional information about children’s privacy.
        </Typography>

        <Divider sx={{ my: 3 }} />

        <Typography variant="h6" gutterBottom>
          8) Educational institutions (FERPA)
        </Typography>
        <Typography variant="body1" component="p">
          If your school uses the App, please see our{' '}
          <Link component={RouterLink} to={ROUTES.FERPA}>
            FERPA notice
          </Link>{' '}
          for more details.
        </Typography>

        <Divider sx={{ my: 3 }} />

        <Typography variant="h6" gutterBottom>
          9) Your choices and requests
        </Typography>
        <List dense sx={{ mb: 2 }}>
          <ListItem>
            <ListItemText
              primary="Account choices"
              secondary="You can use the App anonymously, or you can sign in (Google/email link) to sync across devices."
            />
          </ListItem>
          <ListItem>
            <ListItemText
              primary="Access / deletion"
              secondary="You may request access to or deletion of your information. The fastest way is to contact us via the in-app Feedback button; include the email you use for sign-in (if applicable)."
            />
          </ListItem>
          <ListItem>
            <ListItemText
              primary="Analytics controls"
              secondary="Some analytics controls may be available through your device/browser settings (e.g., blocking cookies or scripts)."
            />
          </ListItem>
        </List>

        <Divider sx={{ my: 3 }} />

        <Typography variant="h6" gutterBottom>
          10) Changes to this policy
        </Typography>
        <Typography variant="body1" component="p">
          We may update this Privacy Policy from time to time. We will change
          the “Last updated” date above and may provide additional notice in the
          App if required.
        </Typography>

        <Divider sx={{ my: 3 }} />
        <Typography variant="h6" gutterBottom>
          11) Contact
        </Typography>
        <Typography variant="body1" component="p">
          Questions or requests? Use the in-app Feedback button or email us at{' '}
          <Link href="mailto:support@mathbuilders.com">
            support@mathbuilders.com
          </Link>{' '}
        </Typography>
      </Paper>
    </Container>
  )
}

export default PrivacyPolicyPage
